import homeprojecticon from '../Graphics/rightchevron.png'
import _certificate from '../Graphics/certificate.png'
import _clayconn from '../Graphics/clayconn.svg'
import _constructing from '../Graphics/constructing.png'
import _house from '../Graphics/house.png'

export const Questions = [
    {questionText : 'This project is for a Home', 
    id : 0, 
    nextPage : 1,
    icon : _house},
    {questionText : 'This project is for a Business', 
    id : 1, 
    nextPage : 6,
    icon : _constructing},
    {questionText : 'Trade Permits', 
    id : 2, 
    nextPage : 1,
    icon : _certificate},
    {questionText : 'Demolition', 
    id : 3, 
    nextPage : 1,
    icon : _house},
    {questionText : 'New Dwelling Construction', 
    id : 4, 
    nextPage : 2,
    icon : _house},
    {questionText : 'Misc Residential Permits', 
    id : 5, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Addition', 
    id : 6, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Interior Alteration', 
    id : 7, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Deck', 
    id : 8, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Detached garage or carport', 
    id : 9, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Pool, hot tup, or spa', 
    id : 10, 
    nextPage : 4,
    icon : _house},
    {questionText : 'Solar Panels', 
    id : 11, 
    nextPage : 5,
    icon : _house},
    {questionText : 'Shed or pole barn', 
    id : 12, 
    nextPage : 3,
    icon : _house},
    {questionText : 'New Single Family Dwelling',
    id : 13, 
    nextPage : 3,
    icon : _house},
    {questionText : 'New Townhouse',
    id : 14, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Flagpole',
    id : 15, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Fireplace',
    id : 16, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Gazebo',
    id : 17, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Pool House',
    id : 18, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Pellet Stove',
    id : 19, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Retaining Stove',
    id : 20, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Pool',
    id : 21, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Spa/Hot tub',
    id : 22, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Ground mounted',
    id : 23, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Roof mounted',
    id : 24, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Change of Occupancy',
    id : 25, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Commercial Alterations',
    id : 26, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Commercial Additions',
    id : 27, 
    nextPage : 3,
    icon : _house},
    {questionText : 'New Commercial Building',
    id : 28, 
    nextPage : 3,
    icon : _house},
    {questionText : 'Miscellaneous Commercial Permits',
    id : 29, 
    nextPage : 3,
    icon : _house}
    ];

    //each array is a 'group' of cards displayed on screen at one time, values are the index of the 'Questions' array above.
export const QuestionGroups = [[0,1,2,3],[4,5,6,7,8,9,10,11,12],[13,14],[15,16,17,18,19,20],[21,22],[23,24],[25,26,27,28,29]];