version: '3.7'

services:
  db:
    image: 'postgis/postgis:14-3.2'
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=doitwebdev01
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
#  server:
#    build: ./elcamino/server
#    ports: 
#      - '3001:3001'
#  client:
#    build: ./elcamino/client
#    ports: 
#      - '443:443'


volumes:
  db_data: