import _24rightchevron from '../graphics/24rightchevron.png'
import _32rightchevron from '../graphics/32rightchevron.png'
import _clayconn from '../graphics/clayconn.svg'
import _clayton from '../graphics/clayton.svg'
import _claytonwhite from '../graphics/claytonwhite.svg'
import _add_new from '../graphics/icons8-add-new-50.png'
import _building_with_rooftop_terrace from '../graphics/icons8-building-with-rooftop-terrace-50.png'
import _city from '../graphics/icons8-city-50.png'
import _company from '../graphics/icons8-company-50.png'
import _contract from '../graphics/icons8-contract-50.png'
import _foundation from '../graphics/icons8-foundation-50.png'
import _hammer from '../graphics/icons8-hammer-50.png'
import _house from '../graphics/icons8-house-50.png'
import _jackhammer from '../graphics/icons8-jackhammer-50.png'
import _jigsaw from '../graphics/icons8-jigsaw-50.png'
import _paint_brush from '../graphics/icons8-paint-brush-50.png'
import _paint_roller from '../graphics/icons8-paint-roller-50.png'
import _pallet from '../graphics/icons8-pallet-50.png'
import _plus from '../graphics/icons8-plus-50.png'
import _prefab_house from '../graphics/icons8-prefab-house-50.png'
import _roof_tiles from '../graphics/icons8-roof-tiles-50.png'
import _roofing from '../graphics/icons8-roofing-50.png'
import _sawing_man from '../graphics/icons8-sawing-man-50.png'
import _small_business from '../graphics/icons8-small-business-50.png'
import _tools from '../graphics/icons8-tools-50.png'
import _logo from '../graphics/logo.svg'
import _rightchevron from '../graphics/rightchevron.png'
export const requirementGroups = [[0,1,2]]
export const prereqs = ['Site Plan','Survey (For Fence: Plat or Tax Map)','Flood Elevation Certificate (If Appliable)','*Environmental Health','Contractor Affidavits','Energy Code Compliance Certificate','Sewer Bond','Floor Plan','Variance (If Applicable)','Grading Permit (If applicable)','State License','Business License','Authorized Agent Form   (If Applicable)','Homeowner Affidavit (If Applicable','Identification','HVAC Letter','Engineering Letter  (If Applicable)','Mobile Home Registration','Mobile Home Tax Receipt','Property Tax Verification','Refund Request Letter','Cash Bond Required','Event Route','Elevations w/ Finish Materials','Police Approval','Fire Marshal Permit','GDOT / County T&D Permit'];
export const Questions = [
    {questionText : 'Commercial building', 
    id : 0, 
    nextPage : 1,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 0},
    {questionText : 'Residential building', 
    id : 1, 
    nextPage : 2,
    icon : _small_business,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Demolition', 
    id : 2, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Electrical', 
    id : 3, 
    nextPage : 4,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Mechanical', 
    id : 4, 
    nextPage : 5,
    icon : _sawing_man,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Plumbing', 
    id : 5, 
    nextPage : 6,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Sign', 
    id : 6, 
    nextPage : 7,
    icon : _prefab_house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Accessory structure', 
    id : 7, 
    nextPage : 0,
    icon : _tools,
    endpagetext : 'An accessory structure is a structure which is on the same parcel of property as a principal structure and the use of which is incidental to the use of the principal structure. For example a residential structure may have a detached garage or storage shed for garden tools as accessory structures',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Addition', 
    id : 8, 
    nextPage : 0,
    icon : _pallet,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Building shell', 
    id : 9, 
    nextPage : 1,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Communication tower upgrade', 
    id : 10, 
    nextPage : 4,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Industrial', 
    id : 11, 
    nextPage : 5,
    icon : _roofing,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'New communication tower', 
    id : 12, 
    nextPage : 3,
    icon : _prefab_house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Office/Institutional',
    id : 13, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Places of worship',
    id : 14, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Renovation/Alteration',
    id : 15, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Retail',
    id : 16, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Accessory dwelling',
    id : 17, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Accessory structure',
    id : 18, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Addition',
    id : 19, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'House moving, into the county',
    id : 20, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'House moving, out/thru the county',
    id : 21, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Mobile home',
    id : 22, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Model home',
    id : 23, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'New home',
    id : 24, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Renovation/Alteration',
    id : 25, 
    nextPage : 3,
    icon : _company,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Demolition not to rebuild',
    id : 26, 
    nextPage : 3,
    icon : _tools,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Demolition to rebuild',
    id : 27, 
    nextPage : 3,
    icon : _hammer,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Facade demolition',
    id : 28, 
    nextPage : 3,
    icon : _city,
    endpagetext : '',
    endpagelink : 'https://selfservice.claytoncountyga.gov/EnerGovProd/SelfService#/businessLicense/apply/business/149',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Interior demolition',
    id : 29, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Commericial new',
    id : 30, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Commercial stand alone',
    id : 31, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Low voltage',
    id : 32, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Reconnect_disconnect only',
    id : 33, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential New',
    id : 34, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential stand alone',
    id : 35, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Temporary utility - electrical',
    id : 36, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},    
    {questionText : 'Commericial New',
    id : 37, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Commerical stand alone',
    id : 38, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Duct work only',
    id : 39, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Gas reconnect',
    id : 40, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential new',
    id : 41, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential stand alone',
    id : 42, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Temporary utility - mechanicial',
    id : 43, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Commericial New',
    id : 44, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Commerical stand alone',
    id : 45, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Gas reconnect',
    id : 46, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential new',
    id : 47, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential stand alone',
    id : 48, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Sprinkler',
    id : 49, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Temporary utility - plumbing',
    id : 50, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'New signage',
    id : 51, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Reface existing sign',
    id : 52, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Repair existing sign',
    id : 53, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Temporary sign',
    id : 54, 
    nextPage : 3,
    icon : _contract,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'}
    ];

    //each array is a 'group' of cards displayed on screen at one time, values are the index of the 'Questions' array above.
export const QuestionGroups = [[0,1,2,3,4,5,6],[7,8,9,10,11,12,13,14,15,16],[17,18,19,20,21,22,23,24,25],[26,27,28,29],[30,31,32,33,34,35,36],[37,38,39,40,41,42,43],[44,45,46,47,48,49,50],[51,52,53,54]];

