import _24rightchevron from '../graphics/24rightchevron.png'
import _32rightchevron from '../graphics/32rightchevron.png'
import _logo from '../graphics/logo.svg'
import _rightchevron from '../graphics/rightchevron.png'

import _celltowernew from '../graphics/cell-tower-new.png'
import _celltowerupgrade from '../graphics/cell-tower-upgrade.png'
import _commercialbuilding from '../graphics/commercial-building.png'
import _company from '../graphics/company.png'
import _factory from '../graphics/factory.png'
import _firesprinkler from '../graphics/fire-sprinkler.png'
import _garage from '../graphics/garage.png'
import _house from '../graphics/house.png'
import _househouse from '../graphics/house-house.png'
import _jackhammer from '../graphics/jackhammer.png'
import _lightning from '../graphics/lightning.png'
import _mechanical from '../graphics/mechanical.png'
import _mobilehome from '../graphics/mobile-home.png'
import _office from '../graphics/office.png'
import _plumbing from '../graphics/plumbing.png'
import _plus from '../graphics/plus.png'
import _prefabhome from '../graphics/prefab-home.png'
import _religion from '../graphics/religion.png'
import _shop from '../graphics/shop.png'
import _signfix from '../graphics/sign-fix.png'
import _signnew from '../graphics/sign-new.png'
import _signresurface from '../graphics/sign-resurface.png'
import _signtemporary from '../graphics/sign-temporary.png'
import _sign from '../graphics/sign.png'
import _structural from '../graphics/structural.png'
import _tools from '../graphics/tools.png'
import _truckhouse from '../graphics/truck-house.png'

export const requirementGroups = [[1,8,14],[0,2,7,8,9,10,11,12,14,23],[0,7,9,10,11,12,14,23],[0,7,9,10,11,12,14,16,23],[0,7,9,10,11,12,14,23],[0,8,9,10,11,12,14,16],[0,9,10,11,12,14,23],[0,8,9,10,11,12,14,23],[7,10,11,12,14,23],[0,7,8,9,10,11,12,14,23],[0,3,4,5,7,8,9,10,11,12,14,23],[1,3,8,9,10,11,12,13,14],[0,1,3,4,8,9,10,11,12,13,14,22,26],[1,2,3,4,5,6,7,8,9,10,11,12,14,21,22,23,26],[10,11,14,19,21,23,26],[10,11,14,17,18,19],[10,11,14,17,18],[0,2,3,4,5,6,7,8,9,10,11,12,13,14,23],[6,10,11,12,13,14,23],[11,14,19,20,21],[11,14],[0,10,11,23],[0],[10,11,14],[10,11],[10,11,14],[14],[10,11,14],[10,11,14],[10,11,14],[10,11,14],[10,11,14],[10,11,14],[10,11,14],[],[10,11,14],[],[10,11,14],[10,11,14],[10,11,14],[4,10,11,14],[10,11,14],[],[],[],[],[],[],[3,22,24,25,26]]
export const prereqs = ['Site Plan','Survey (For Fence: Plat or Tax Map)','Flood Elevation Certificate (If Appliable)','*Environmental Health','Contractor Affidavits','Energy Code Compliance Certificate','Sewer Bond','Floor Plan','Variance (If Applicable)','Grading Permit (If applicable)','State License','Business License','Authorized Agent Form   (If Applicable)','Homeowner Affidavit (If Applicable','Identification','HVAC Letter','Engineering Letter  (If Applicable)','Mobile Home Registration','Mobile Home Tax Receipt','Property Tax Verification','Refund Request Letter','Cash Bond Required','Event Route','Elevations w/ Finish Materials','Police Approval','Fire Marshal Permit','GDOT / County T&D Permit'];
export const Questions = [
    {questionText : 'Commercial building', 
    id : 0, 
    nextPage : 1,
    icon : _company,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 0},
    {questionText : 'Residential building', 
    id : 1, 
    nextPage : 2,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Demolition', 
    id : 2, 
    nextPage : 3,
    icon : _jackhammer,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Electrical', 
    id : 3, 
    nextPage : 4,
    icon : _lightning,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Mechanical', 
    id : 4, 
    nextPage : 5,
    icon : _mechanical,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Plumbing', 
    id : 5, 
    nextPage : 6,
    icon : _plumbing,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Sign', 
    id : 6, 
    nextPage : 7,
    icon : _sign,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Accessory structure', 
    id : 7, 
    nextPage : 0,
    icon : _garage,
    endpagetext : 'An accessory structure is a structure which is on the same parcel of property as a principal structure and the use of which is incidental to the use of the principal structure. For example a residential structure may have a detached garage or storage shed for garden tools as accessory structures',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Addition', 
    id : 8, 
    nextPage : 0,
    icon : _plus,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : false,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Building shell', 
    id : 9, 
    nextPage : 1,
    icon : _structural,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Communication tower upgrade', 
    id : 10, 
    nextPage : 4,
    icon : _celltowerupgrade,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Industrial', 
    id : 11, 
    nextPage : 5,
    icon : _factory,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'New communication tower', 
    id : 12, 
    nextPage : 3,
    icon : _celltowernew,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Office/Institutional',
    id : 13, 
    nextPage : 3,
    icon : _office,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Places of worship',
    id : 14, 
    nextPage : 3,
    icon : _religion,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Renovation/Alteration',
    id : 15, 
    nextPage : 3,
    icon : _tools,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Retail',
    id : 16, 
    nextPage : 3,
    icon : _shop,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Accessory dwelling',
    id : 17, 
    nextPage : 3,
    icon : _househouse,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Accessory structure',
    id : 18, 
    nextPage : 3,
    icon : _garage,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Addition',
    id : 19, 
    nextPage : 3,
    icon : _plus,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'House moving, into the county',
    id : 20, 
    nextPage : 3,
    icon : _truckhouse,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'House moving, out/thru the county',
    id : 21, 
    nextPage : 3,
    icon : _truckhouse,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Mobile home',
    id : 22, 
    nextPage : 3,
    icon : _mobilehome,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Model home',
    id : 23, 
    nextPage : 3,
    icon : _prefabhome,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'New home',
    id : 24, 
    nextPage : 3,
    icon : _house,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Renovation/Alteration',
    id : 25, 
    nextPage : 3,
    icon : _tools,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Demolition not to rebuild',
    id : 26, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Demolition to rebuild',
    id : 27, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Facade demolition',
    id : 28, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : 'https://selfservice.claytoncountyga.gov/EnerGovProd/SelfService#/businessLicense/apply/business/149',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Interior demolition',
    id : 29, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Commericial new',
    id : 30, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Commercial stand alone',
    id : 31, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Low voltage',
    id : 32, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Reconnect_disconnect only',
    id : 33, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential New',
    id : 34, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential stand alone',
    id : 35, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Temporary utility - electrical',
    id : 36, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},    
    {questionText : 'Commericial New',
    id : 37, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Commerical stand alone',
    id : 38, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Duct work only',
    id : 39, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Gas reconnect',
    id : 40, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential new',
    id : 41, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential stand alone',
    id : 42, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Temporary utility - mechanicial',
    id : 43, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Commericial New',
    id : 44, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Commerical stand alone',
    id : 45, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Gas reconnect',
    id : 46, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential new',
    id : 47, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Residential stand alone',
    id : 48, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Sprinkler',
    id : 49, 
    nextPage : 3,
    icon : _firesprinkler,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Temporary utility - plumbing',
    id : 50, 
    nextPage : 3,
    icon : '',
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'New signage',
    id : 51, 
    nextPage : 3,
    icon : _signnew,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Reface existing sign',
    id : 52, 
    nextPage : 3,
    icon : _signresurface,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Repair existing sign',
    id : 53, 
    nextPage : 3,
    icon : _signfix,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'},
    {questionText : 'Temporary sign',
    id : 54, 
    nextPage : 3,
    icon : _signtemporary,
    endpagetext : '',
    endpagelink : '',
    price : '',
    addinfo : '',
    endpage : true,
    requirements : 'Survey (For Fence: Plat or Tax Map)'}
    ];

    //each array is a 'group' of cards displayed on screen at one time, values are the index of the 'Questions' array above.
export const QuestionGroups = [[0,1,2,3,4,5,6],[7,8,9,10,11,12,13,14,15,16],[17,18,19,20,21,22,23,24,25],[26,27,28,29],[30,31,32,33,34,35,36],[37,38,39,40,41,42,43],[44,45,46,47,48,49,50],[51,52,53,54]];

