export const prereqs = [
    'Site Plan',
    'Survey',
    'Flood Elevation Certificate (If Appliable)',
    '*Environmental Health',
    'Contractor Affidavits',
    'Energy Code Compliance Certificate',
    'Sewer Bond',
    'Floor Plan',
    'Variance (If Applicable)',
    'Grading Permit (If applicable)',
    'State License',
    'Business License',
    'Authorized Agent Form (If Applicable)',
    'Homeowner Affidavit (If Applicable',
    'Identification',
    'HVAC Letter',
    'Engineering Letter (If Applicable)',
    'Mobile Home Registration',
    'Mobile Home Tax Receipt',
    'Property Tax Verification',
    'Refund Request Letter',
    'Cash Bond Required',
    'Event Route',
    'Elevations w/ Finish Materials',
    'Police Approval',
    'Fire Marshal Permit',
    'GDOT / County T&D Permit'
    ];