export const prereqs = [
    {id : 0, name : 'Site Plan'},
    {id : 1, name : 'Survey'},
    {id : 2, name : 'Flood Elevation Certificate (If Appliable)'},
    {id : 3, name : '*Environmental Health'},
    {id : 4, name : 'Contractor Affidavits'},
    {id : 5, name : 'Energy Code Compliance Certificate'},
    {id : 6, name : 'Sewer Bond'},
    {id : 7, name : 'Floor Plan'},
    {id : 8, name : 'Variance (If Applicable)'},
    {id : 9, name : 'Grading Permit (If applicable)'},
    {id : 10, name : 'State License'},
    {id : 11, name : 'Business License'},
    {id : 12, name : 'Authorized Agent Form (If Applicable)'},
    {id : 13, name : 'Homeowner Affidavit (If Applicable'},
    {id : 14, name : 'Identification'},
    {id : 15, name : 'HVAC Letter'},
    {id : 16, name : 'Engineering Letter (If Applicable)'},
    {id : 17, name : 'Mobile Home Registration'},
    {id : 18, name : 'Mobile Home Tax Receipt'},
    {id : 19, name : 'Property Tax Verification'},
    {id : 20, name : 'Refund Request Letter'},
    {id : 21, name : 'Cash Bond Required'},
    {id : 22, name : 'Event Route'},
    {id : 23, name : 'Elevations w/ Finish Materials'},
    {id : 24, name : 'Police Approval'},
    {id : 25, name : 'Fire Marshal Permit'},
    {id : 26, name : 'GDOT / County T&D Permit'}
    ];